---
name: DBT-deployment
on:
  push:
    branches:
      - main
jobs:
  trigger-lambda-function:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: get the latest committed files
        run: |
          git config --global --add safe.directory '*'
          pwd
          ls -la
          git checkout main
          unset LESS
          echo "this is diff"
          DIFF=$(git diff-tree --no-commit-id --name-only -r HEAD --no-renames)
          echo $DIFF
          echo "this is payload"
          PAYLOAD=$(base64 <<< "{\"updated_files\": \"$DIFF\"}")
          echo $PAYLOAD
          aws lambda invoke --function-name github_ci_cd --payload "$PAYLOAD" output.json
