name: DBT-deployment

on:
  push:
    branches:
      - main

jobs:

  trigger-lambda-function:
    runs-on: ubuntu-latest
    container:
      image: amazon/aws-cli
    steps:
      - name: install tar
        run: |
          yum install -y tar gzip
          yum install -y git

      - uses: actions/checkout@v3

      - name: get the latest commit
        run: |
          pwd
          latest_commit=$(git rev-parse HEAD)
          echo $latest_commit
          list_of_files=$(git diff --name-only $latest_commit)
          echo $list_of_files
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set aws_region us-east-1
          aws sts get-caller-identity
          #aws s3 ls
          #aws lambda invoke --function-name github_ci_cd --payload $list_of_files
